[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
# solidity_version = "0.8.19"

# [profile.eth_rpc_endpoints]
# default = "http://localhost:8545"

[fmt]
# Solidity style guide
bracket_spacing = false
int_types = "short"
line_length = 100

[doc]
infer_rem = true
solc = "0.8.19"