[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solidity_version = "0.8.20"

optimizer = true
optimizer_runs = 200
runs = 200
viaIR = true

[fmt]
# Solidity style guide
bracket_spacing = false
int_types = "short"
line_length = 100

[doc]
infer_rem = true
solc = "0.8.20"